run:
	python3 Map_Comparison.py

clean:
	rm aligned_cartographer.png \
    aligned_slam.png \
    aligned_drawn.png \
    aligned_overlay_preview.png \
    pre_cartographer_500.png \
    pre_slam_500.png \
    pre_drawn_500.png