run:
	python3 Map_Comparison.py

clean:
	rm -f pre_drawn_500.png \
	aligned_drawn.png \
	cartographer_aligned_*.png \
	slam_aligned_*.png \
	cartographer_average.png \
	slam_average.png \
	overlay_cartographer_avg_vs_groundtruth.png \
	overlay_slam_avg_vs_groundtruth.png \
	results_table.txt \
	results_table.csv